version: "3.3"
services:
  core:
    build: .
    ports:
      - "5000:5000"
      - "2222:2222"
      # Mount the current working directory into the container as /opt/mojobol
    volumes:
      - ../mojobol:/opt/mojobol
